# One Dark Monokai - Deep Minimal
foreground #e3e3e3
background #101010

# Black & Muted Dark Grays
color0 #1a1a1a
color8 #3a3a3a

# Red -> Soft Pastel Rose (Visible but muted)
color1 #cc8897
color9 #cc8897

# Green -> Soft Sage/Mint (Clean and readable, not muddy)
color2  #9bb388
color10 #9bb388

# Yellow -> Muted Straw
color3  #d1c4a5
color11 #d1c4a5

# Blue -> Soft Slate Blue
color4  #839bb0
color12 #839bb0

# Magenta -> Pale Lavender
color5  #a19ba8
color13 #a19ba8

# Cyan -> Soft Opal/Teal
color6  #8baab0
color14 #8baab0

# White & Light Grays
color7  #a0a0a0
color15 #ffffff

# Cursor
cursor #8baab0
cursor_text_color #101010

# Selection highlight
selection_foreground none
selection_background #222222

# The color for highlighting URLs on mouse-over
url_color #8baab0

# Window borders
active_border_color #8baab0
inactive_border_color #101010
bell_border_color #d1c4a5

# Tab bar
tab_bar_style fade
tab_fade 1
active_tab_foreground   #8baab0
active_tab_background   #101010
active_tab_font_style   normal
inactive_tab_foreground #4a4a4a
inactive_tab_background #101010
inactive_tab_font_style normal
tab_bar_background      #101010

# Title bar (macOS)
macos_titlebar_color #101010
