# One Dark Monokai - Deep Dark
foreground #e3e3e3
background #101010

# Black
color0 #282c34
color8 #5c6370

# Red
color1 #ff6188
color9 #ff6188

# Green
color2  #a9dc76
color10 #a9dc76

# Yellow
color3  #ffd866
color11 #ffd866

# Blue
color4  #61afef
color12 #61afef

# Magenta
color5  #ab9df2
color13 #ab9df2

# Cyan
color6  #78dce8
color14 #78dce8

# White
color7  #abb2bf
color15 #ffffff

# Cursor
cursor #ab9df2
cursor_text_color #101010

# Selection highlight
selection_foreground none
selection_background #2c313a

# The color for highlighting URLs on mouse-over
url_color #a9dc76

# Window borders
active_border_color #ab9df2
inactive_border_color #101010
bell_border_color #ffd866

# Tab bar
tab_bar_style fade
tab_fade 1
active_tab_foreground   #ab9df2
active_tab_background   #101010
active_tab_font_style   bold
inactive_tab_foreground #5c6370
inactive_tab_background #101010
inactive_tab_font_style bold
tab_bar_background      #080808

# Title bar (macOS)
macos_titlebar_color #101010
